before_script:
  - git config --global --add safe.directory "C:/GitLab-Runner/builds/A2X5hgzdb/0/I525452/torquehubfe"

stages:
  - install
  - test
  - build
  - dockerize

install:
  stage: install
  script:
    - npm install --legacy-peer-deps

test:
  stage: test
  script:
    - npm test -- --watchAll=false

build:
  stage: build
  script:
    - $env:CI = "false"
    - npm install
    - npm run build
    - npm ci

dockerize:
  stage: dockerize
  needs: 
    - job: build
  script:
    - $registry = "$env:CI_REGISTRY_IMAGE"
    - docker build -t my-react-app .
