stages:
  - build
  - dockerize

# Build Stage
build:
  stage: build
  script:
    - $env:CI = "false" # Ensure CI environment is set to false
    - npm install ajv ajv-keywords --legacy-peer-deps
    - npm install --legacy-peer-deps
    - npm run build # Build the React app
  artifacts:
    paths:
      - build/ # Save the build directory for the next stages

# Dockerize Stage
dockerize:
  stage: dockerize
  dependencies:
    - build 
  script:
    - docker build -t my-react-app .
    - docker push $CI_REGISTRY_IMAGE
