stages:
  - build
  - test
  - dockerize

build:
  stage: build
  script:
    - $env:CI = "false"
    - npm install ajv ajv-keywords --legacy-peer-deps
    - npm install --legacy-peer-deps
    - npm run build
    - npm ci
test:
  stage: test
  script:
    - npm test -- --watchAll=false



dockerize:
  stage: dockerize
  needs: 
    - job: build
  script:
    - $registry = "$env:CI_REGISTRY_IMAGE"
    - docker build -t my-react-app .
