stages:
  - build
  - test
  - dockerize

# Build Stage
build:
  stage: build
  script:
    - $env:CI = "false" # Ensure CI environment is set to false
    - npm install --legacy-peer-deps
    - npm run build # Build the React app
  artifacts:
    paths:
      - build/ # Save the build directory for the next stages

test:
  stage: test
  script:
    - npm test -- --watchAll=false

# Dockerize Stage
dockerize:
  stage: dockerize
  dependencies:
    - build 
  script:
    - $registry = "$env:CI_REGISTRY_IMAGE"
    - docker build -t my-react-app .
