concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "martiParty"
  url = "https://git.fhict.nl"
  id = 10469
  token = "glrt-VuRY4A8xDhu_AUfzCNPF"
  token_obtained_at = 2024-11-25T12:35:18Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
