[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  # Pass --legacy-peer-deps to every npm install
  NPM_FLAGS   = "--legacy-peer-deps"
  CI = "false"

# Optional: set the npm‑level env var if you want belt‑and‑braces
# npm_config_legacy_peer_deps = "true"

[build.lifecycle]
  # Still installing the platform‑specific esbuild binary
  onPreBuild = "npm install @esbuild/linux-x64 --no-save || true"

# Handle OPTIONS preflight requests for API
[[redirects]]
  from = "/api/*"
  to = "https://backend.torque-hub.com/api/:splat"
  status = 200
  force = true
  conditions = {method = "OPTIONS"}
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "*", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Main API redirect with credentials support
[[redirects]]
  from = "/api/*"
  to = "https://backend.torque-hub.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Credentials = "true", Access-Control-Expose-Headers = "Content-Length, X-Total-Count"}

# Handle OPTIONS preflight requests for showcase-api
[[redirects]]
  from = "/showcase-api/*"
  to = "https://backend.torque-hub.com/showcase-api/:splat"
  status = 200
  force = true
  conditions = {method = "OPTIONS"}
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "*", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Main showcase-api redirect with credentials support
[[redirects]]
  from = "/showcase-api/*"
  to = "https://backend.torque-hub.com/showcase-api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Credentials = "true", Access-Control-Expose-Headers = "Content-Length, X-Total-Count"}

# Handle OPTIONS preflight requests for ticket-api
[[redirects]]
  from = "/ticket-api/*"
  to = "https://backend.torque-hub.com/ticket-api/:splat"
  status = 200
  force = true
  conditions = {method = "OPTIONS"}
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "*", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Main ticket-api redirect with credentials support
[[redirects]]
  from = "/ticket-api/*"
  to = "https://backend.torque-hub.com/ticket-api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Credentials = "true", Access-Control-Expose-Headers = "Content-Length, X-Total-Count"}

# WebSocket support with improved handling
[[redirects]]
  from = "/ws/*"
  to = "wss://backend.torque-hub.com/ws/:splat"
  status = 101
  force = true
  headers = {Access-Control-Allow-Origin = "https://torque-hub.com", Access-Control-Allow-Credentials = "true"}

# Cache headers (unchanged)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://backend.torque-hub.com wss://backend.torque-hub.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;"

# This needs to be the last redirect so that it doesn't override other redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 