[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  # Pass --legacy-peer-deps to every npm install
  NPM_FLAGS   = "--legacy-peer-deps"

# Optional: set the npm‑level env var if you want belt‑and‑braces
# npm_config_legacy_peer_deps = "true"

[build.lifecycle]
  # Still installing the platform‑specific esbuild binary
  onPreBuild = "npm install @esbuild/linux-x64 --no-save || true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache headers (unchanged)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
